// reviewActionTypes.js

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const GET_REVIEWS_FOR_RESTAURANT = 'GET_REVIEWS_FOR_RESTAURANT';
export const GET_REVIEWS_BY_USER = 'GET_REVIEWS_BY_USER';
export const REVIEW_ERROR = 'REVIEW_ERROR';
